import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { SocketProvider } from "@/context/SocketContext";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={` bg-black text-white ${rubik.className}`}>
        <SocketProvider>{children}</SocketProvider>
      </body>
    </html>
  );
}
